#
# sdl/makefile.cfg for SRB2/SDL
#

#
#SDL...., *looks at Alam*, THIS IS A MESS!
#

ifdef UNIXCOMMON
include sdl/MakeNIX.cfg
endif

ifdef PANDORA
include sdl/SRB2Pandora/Makefile.cfg
endif #ifdef PANDORA

ifdef CYGWIN32
include sdl/MakeCYG.cfg
endif #ifdef CYGWIN32

ifdef SDL_PKGCONFIG
SDL_CFLAGS?=$(shell $(PKG_CONFIG) $(SDL_PKGCONFIG) --cflags)
SDL_LDFLAGS?=$(shell $(PKG_CONFIG) $(SDL_PKGCONFIG) --libs)
else
ifdef PREFIX
	SDL_CONFIG?=$(PREFIX)-sdl2-config
else
	SDL_CONFIG?=sdl2-config
endif

ifdef STATIC
	SDL_CFLAGS?=$(shell $(SDL_CONFIG) --cflags)
	SDL_LDFLAGS?=$(shell $(SDL_CONFIG) --static-libs)
else
	SDL_CFLAGS?=$(shell $(SDL_CONFIG) --cflags)
	SDL_LDFLAGS?=$(shell $(SDL_CONFIG) --libs)
endif
endif


	#use the x86 asm code
ifndef CYGWIN32
ifndef NOASM
	USEASM=1
endif
endif

	OBJS+=$(OBJDIR)/i_video.o $(OBJDIR)/dosstr.o $(OBJDIR)/endtxt.o $(OBJDIR)/hwsym_sdl.o

	OPTS+=-DDIRECTFULLSCREEN -DHAVE_SDL

# Raw cellGcm video backend for PS3 (bypasses SDL2_PSL1GHT's video/render
# path entirely -- see sdl/i_video_ps3_gcm.h). Needs PS3DEV to be set
# (sourced from PS3DK's scripts/env.sh) for its include/lib paths.
ifdef PS3GCM
	OBJS+=$(OBJDIR)/i_video_ps3_gcm.o
	OPTS+=-I$(PS3DEV)/ps3dk/ppu/include
	# -lgcm_cmd is here for ps3tc_fifo_wrap_install() alone: PS3DK's replacement
	# command-FIFO wrap callback. See PS3GCM_VideoInit for why we need it.
	LIBS+=-L$(PS3DEV)/ps3dk/ppu/lib -lrsx -lgcm_cmd -lgcm_sys -lsysutil
endif

# 2026-09-05 -- bissection du non-demarrage OpenGL sur console reelle.
#
# Le build LOGICIEL demarre chez Alex, le build OPENGL n'ecrit rien (meme pas
# son constructeur statique), et retirer l'import PRX sys_fs n'a rien change.
# Il ne reste que deux differences entre les deux binaires : la presence du
# code PSGL, et 16 Mo de BSS en plus (tex[2048*2048] de r_opengl.c:1552).
#
# Ces deux drapeaux ajoutent UNE SEULE de ces differences a un build logiciel
# connu bon, pour savoir laquelle tue le chargement. Ils sont temporaires.
#
#   PS3_BSS_PROBE=1  -> +16 Mo de BSS, pas une ligne de PSGL
#   PS3_FORCE_PSGL=1 -> tout PSGL dans le binaire, BSS inchange
#
# --whole-archive parce qu'un build logiciel n'appelle aucune entree GL : sans
# lui le lieur n'extrairait aucun objet de libPSGL.a et la variante ne testerait
# rien. i_ps3_cellfs.o accompagne PSGL pour ses quatre cellFs* (voir ce fichier)
# et garde la table d'imports PRX identique a celle du logiciel.
ifdef PS3_BSS_PROBE
	OBJS+=$(OBJDIR)/i_ps3_bssprobe.o
	OPTS+=-DPS3_BSS_PROBE_MB=$(PS3_BSS_PROBE)
endif
ifdef PS3_FORCE_PSGL
	OBJS+=$(OBJDIR)/i_ps3_cellfs.o
	LIBS+=-Wl,--whole-archive -lPSGL -Wl,--no-whole-archive -lPSGLU -lcgb -lgcm_cmd -lgcm_sys -lrsx -lsysutil_stub -lsysutil -lm
endif

ifndef NOHW
ifdef PS3GCM
	# 2026-09-02 -- sur PS3 le contexte GL vient de PSGL, pas de SDL : ogl_psgl.c
	# remplace ogl_sdl.c (memes prototypes, meme role).
	#
	# STATIC_OPENGL parce que PSGL est une bibliotheque statique et qu'il n'y a
	# pas de chargeur dynamique ici. Sous ce drapeau les entrees GL de base se
	# resolvent a l'edition de liens ; seules les neuf de SetupGLFunc4 passent
	# par le GetGLFunc d'ogl_psgl.c, qui est une simple table.
	#
	# -I ps3/glcompat rebranche <GL/gl.h> sur <GLES/gl.h> et fournit les rares
	# equivalents que GLES n'a pas -- voir ps3/glcompat/GL/gl.h pour la liste et
	# pour les trous connus (glTexEnvi, glMultiTexCoord4f, GL_VIEWPORT).
	OBJS+=$(OBJDIR)/r_opengl.o $(OBJDIR)/ogl_psgl.o
	OPTS+=-I$(PS3DK_GLCOMPAT) -DSTATIC_OPENGL
	# L'ORDRE COMPTE : le lieur ne revient pas en arriere dans une archive deja
	# parcourue. PSGL appelle cellGcm*, cellFs* et rsx*, donc ses dependances
	# doivent venir APRES lui. C'est la meme lecon que l'ordre
	# -lSDL2_mixer -lvorbisfile -lvorbis -logg du build audio.
	#
	# 2026-09-05 -- -lfs_stub est la seule raison pour laquelle l'EBOOT OpenGL
	# importe le module PRX sys_fs, que le build LOGICIEL n'importe pas (mesure
	# au readelf : c'est l'unique difference d'imports entre les deux binaires).
	# PS3_LOCAL_CELLFS=1 fournit a la place nos propres cellFs* via les appels
	# POSIX de newlib -- le meme chemin que le build logiciel, celui qui marche
	# sur console reelle. Voir l'en-tete de sdl/i_ps3_cellfs.c.
ifdef PS3_LOCAL_CELLFS
	OBJS+=$(OBJDIR)/i_ps3_cellfs.o
	LIBS+=-lPSGL -lPSGLU -lcgb -lgcm_cmd -lgcm_sys -lrsx -lsysutil_stub -lsysutil -lm
else
	LIBS+=-lPSGL -lPSGLU -lcgb -lgcm_cmd -lgcm_sys -lrsx -lfs_stub -lsysutil_stub -lsysutil -lm
endif
else
	OBJS+=$(OBJDIR)/r_opengl.o $(OBJDIR)/ogl_sdl.o
endif
endif

ifdef NOMIXER
	i_sound_o=$(OBJDIR)/sdl_sound.o
else
	i_sound_o=$(OBJDIR)/mixer_sound.o
	OPTS+=-DHAVE_MIXER
	SDL_LDFLAGS+=-lSDL2_mixer
endif

ifndef NOTHREADS
	OPTS+=-DHAVE_THREADS
	OBJS+=$(OBJDIR)/i_threads.o
endif

ifdef SDL_TTF
	OPTS+=-DHAVE_TTF
	SDL_LDFLAGS+=-lSDL2_ttf -lfreetype -lz
	OBJS+=$(OBJDIR)/i_ttf.o
endif

ifdef SDL_IMAGE
	OPTS+=-DHAVE_IMAGE
	SDL_LDFLAGS+=-lSDL2_image
endif

ifdef SDL_NET
	OPTS+=-DHAVE_SDLNET
	SDL_LDFLAGS+=-lSDL2_net
endif

ifdef MINGW
ifndef NOSDLMAIN
	SDLMAIN=1
endif
endif

ifdef SDLMAIN
	OPTS+=-DSDLMAIN
else
ifdef MINGW
	SDL_CFLAGS+=-Umain
	SDL_LDFLAGS+=-mconsole
endif
endif

ifndef NOHW
ifdef OPENAL
ifdef MINGW
	LIBS:=-lopenal32 $(LIBS)
else
	LIBS:=-lopenal $(LIBS)
endif
else
ifdef MINGW
ifdef DS3D
	LIBS:=-ldsound -luuid $(LIBS)
endif
endif
endif
endif

CFLAGS+=$(SDL_CFLAGS)
LIBS:=$(SDL_LDFLAGS) $(LIBS)
ifdef STATIC
	LIBS+=$(shell $(SDL_CONFIG) --static-libs)
endif
