// SONIC ROBO BLAST 2
//-----------------------------------------------------------------------------
// Copyright (C) 1993-1996 by id Software, Inc.
// Copyright (C) 1998-2000 by DooM Legacy Team.
// Copyright (C) 1999-2018 by Sonic Team Junior.
//
// This program is free software distributed under the
// terms of the GNU General Public License, version 2.
// See the 'LICENSE' file for more details.
//-----------------------------------------------------------------------------
/// \file  d_main.c
/// \brief SRB2 main program
///
///        SRB2 main program (D_SRB2Main) and game loop (D_SRB2Loop),
///        plus functions to parse command line parameters, configure game
///        parameters, and call the startup functions.

#if (defined (__unix__) && !defined (MSDOS)) || defined(__APPLE__) || defined (UNIXCOMMON)
#include <sys/stat.h>
#include <sys/types.h>
#endif

#ifdef __GNUC__
#include <unistd.h> // for getcwd
#endif

#ifdef PC_DOS
#include <stdio.h> // for snprintf
int	snprintf(char *str, size_t n, const char *fmt, ...);
//int	vsnprintf(char *str, size_t n, const char *fmt, va_list ap);
#endif

#if (defined (_WIN32) && !defined (_WIN32_WCE)) && !defined (_XBOX)
#include <direct.h>
#include <malloc.h>
#endif

#if !defined (UNDER_CE)
#include <time.h>
#elif defined (_XBOX)
#define NO_TIME
#endif

#include "doomdef.h"
#include "am_map.h"
#include "console.h"
#include "d_net.h"
#include "f_finale.h"
#include "g_game.h"
#include "hu_stuff.h"
#include "i_sound.h"
#include "i_system.h"
#include "i_time.h"
#include "i_threads.h"
#include "i_video.h"
#include "m_argv.h"
#include "m_menu.h"
#include "m_misc.h"
#include "p_setup.h"
#include "p_saveg.h"
#include "r_main.h"
#include "r_local.h"
#include "s_sound.h"
#include "st_stuff.h"
#include "v_video.h"
#include "w_wad.h"
#include "z_zone.h"
#include "d_main.h"
#include "d_netfil.h"
#include "m_cheat.h"
#include "y_inter.h"
#include "p_local.h" // chasecam
#include "m_misc.h" // screenshot functionality
#include "dehacked.h" // Dehacked list test
#include "m_cond.h" // condition initialization
#include "fastcmp.h"
#include "r_fps.h" // Frame interpolation/uncapped
#include "keys.h"
#include "filesrch.h" // refreshdirmenu

#ifdef CMAKECONFIG
#include "config.h"
#else
#include "config.h.in"
#endif

#ifdef _XBOX
#include "sdl12/SRB2XBOX/xboxhelp.h"
#endif

#ifdef HWRENDER
#include "hardware/hw_main.h" // 3D View Rendering
#endif

#ifdef _WINDOWS
#include "win32/win_main.h" // I_DoStartupMouse
#endif

#ifdef HW3SOUND
#include "hardware/hw3sound.h"
#endif

#ifdef HAVE_BLUA
#include "lua_script.h"
#endif

#ifdef HAVE_DISCORDRPC
#include "discord.h"
#endif

// platform independant focus loss
UINT8 window_notinfocus = false;

//
// DEMO LOOP
//
//static INT32 demosequence;
static const char *pagename = "MAP1PIC";
static char *startupwadfiles[MAX_WADFILES];
static char *startuppwads[MAX_WADFILES];

boolean devparm = false; // started game with -devparm

boolean singletics = false; // timedemo
boolean lastdraw = false;

postimg_t postimgtype[MAXSPLITSCREENPLAYERS];
INT32 postimgparam[MAXSPLITSCREENPLAYERS];

// These variables are only true if
// whether the respective sound system is disabled
// or they're init'ed, but the player just toggled them
#ifdef _XBOX
#ifndef NO_MIDI
boolean midi_disabled = true;
#endif
boolean sound_disabled = true;
boolean digital_disabled = true;
#else
#ifndef NO_MIDI
boolean midi_disabled = false;
#endif
boolean sound_disabled = false;
boolean digital_disabled = false;
#endif

#ifdef DEBUGFILE
INT32 debugload = 0;
#endif

char savegamename[256];

#ifdef _arch_dreamcast
char srb2home[256] = "/cd";
char srb2path[256] = "/cd";
#else
char srb2home[256] = ".";
char srb2path[256] = ".";
#endif
boolean usehome = true;
const char *pandf = "%s" PATHSEP "%s";

//
// EVENT HANDLING
//
// Events are asynchronous inputs generally generated by the game user.
// Events can be discarded if no responder claims them
// referenced from i_system.c for I_GetKey()

event_t events[MAXEVENTS];
INT32 eventhead, eventtail;

boolean dedicated = false;

//
// D_PostEvent
// Called by the I/O functions when input is detected
//
void D_PostEvent(const event_t *ev)
{
	events[eventhead] = *ev;
	eventhead = (eventhead+1) & (MAXEVENTS-1);
}
// just for lock this function
#if defined (PC_DOS) && !defined (DOXYGEN)
void D_PostEvent_end(void) {};
#endif

// modifier keys
// Now handled in I_OsPolling
UINT8 shiftdown = 0; // 0x1 left, 0x2 right
UINT8 ctrldown = 0; // 0x1 left, 0x2 right
UINT8 altdown = 0; // 0x1 left, 0x2 right
boolean capslock = 0;	// gee i wonder what this does.

//
// D_ProcessEvents
// Send all the events of the given timestamp down the responder chain
//
void D_ProcessEvents(void)
{
	event_t *ev;

	boolean eaten;

	for (; eventtail != eventhead; eventtail = (eventtail+1) & (MAXEVENTS-1))
	{
		ev = &events[eventtail];

		// Screenshots over everything so that they can be taken anywhere.
		if (M_ScreenshotResponder(ev))
			continue; // ate the event

		if (gameaction == ga_nothing && gamestate == GS_TITLESCREEN)
		{
			if (cht_Responder(ev))
				continue;
		}

		if (demo.savemode == DSM_TITLEENTRY)
		{
			if (G_DemoTitleResponder(ev))
				continue;
		}

		// Menu input
#ifdef HAVE_THREADS
		I_lock_mutex(&m_menu_mutex);
#endif
		{
			eaten = M_Responder(ev);
		}
#ifdef HAVE_THREADS
		I_unlock_mutex(m_menu_mutex);
#endif

		if (eaten)
			continue; // menu ate the event

		// Demo input:
		if (demo.playback)
			if (M_DemoResponder(ev))
				continue;	// demo ate the event

		// console input
#ifdef HAVE_THREADS
		I_lock_mutex(&con_mutex);
#endif
		{
			eaten = CON_Responder(ev);
		}
#ifdef HAVE_THREADS
		I_unlock_mutex(con_mutex);
#endif

		if (eaten)
			continue; // ate the event

		G_Responder(ev);
	}
}

//
// D_Display
// draw current display, possibly wiping it from the previous
//

// wipegamestate can be set to -1 to force a wipe on the next draw
// added comment : there is a wipe eatch change of the gamestate
gamestate_t wipegamestate = GS_LEVEL;

#ifdef _PS3
extern int ps3_debugtrace; // defined below, next to the profiler
extern int ps3_norender3d; // defined below; bisection knob, see R_RenderPlayerView call
extern int ps3_noaudio;    // defined below; bisection knob, see I_StartupSound call
static int ps3dispcalls = 0;
static boolean ps3dtrace = false;
static void ps3d(const char *msg)
{
	FILE *f;

	// PS3TRACE_DISPLAY_SYNC (bit 4, see d_main.c's ps3_debugtrace block):
	// issue a barrier here instead of writing a line. These 19 call sites are
	// the only thing standing between a working title screen and an RPCS3
	// segfault two intro tics in, and a 60Hz flip pacer imposing the same
	// ~17ms frame does NOT substitute for them -- so it is not frame duration
	// that matters, it is what happens between the draw calls. If a plain
	// "sync" is enough, the fault is a missing serialisation and costs
	// nanoseconds to fix rather than the 903us a trace write costs.
	if (ps3_debugtrace & 16)
	{
		__asm__ __volatile__("sync" ::: "memory");
		return;
	}

	if (!ps3dtrace)
		return;
	f = fopen(PS3_DebugPath("psdebugA.txt"), "a");
	if (f) { fprintf(f, "[disp#%d] %s\n", ps3dispcalls, msg); fflush(f); fclose(f); }
}
#endif

static void D_Display(void)
{
	boolean forcerefresh = false;
	static boolean wipe = false;
	INT32 wipedefindex = 0;
	UINT8 i;

#ifdef _PS3
	ps3dispcalls++;
	ps3dtrace = ((ps3_debugtrace & 2) && ps3dispcalls <= 3000); // PS3TRACE_DISPLAY, defined below
	ps3d("D0 D_Display entry");
#endif

	if (!dedicated)
	{
		if (nodrawers)
			return; // for comparative timing/profiling

		// check for change of screen size (video mode)
		if (setmodeneeded && !wipe)
			SCR_SetMode(); // change video mode

		if (vid.recalc)
			SCR_Recalc(); // NOTE! setsizeneeded is set by SCR_Recalc()

		// change the view size if needed
		if (setsizeneeded)
		{
			R_ExecuteSetViewSize();
			forcerefresh = true; // force background redraw
		}

		// draw buffered stuff to screen
		// Used only by linux GGI version
		I_UpdateNoBlit();
	}

	// save the current screen if about to wipe
	wipe = (gamestate != wipegamestate);
	if (wipe)
	{
		// set for all later
		wipedefindex = gamestate; // wipe_xxx_toblack
		if (gamestate == GS_TITLESCREEN && wipegamestate != GS_INTRO)
			wipedefindex = wipe_timeattack_toblack;
		else if (gamestate == GS_INTERMISSION)
		{
			if (intertype == int_spec) // Special Stage
				wipedefindex = wipe_specinter_toblack;
			else //if (intertype != int_coop) // Multiplayer
				wipedefindex = wipe_multinter_toblack;
		}

		if (!dedicated)
		{
			// Fade to black first
			if (gamestate != GS_LEVEL // fades to black on its own timing, always
			 && wipedefs[wipedefindex] != UINT8_MAX)
			{
#ifdef _PS3
				PS3_Mark("MARK W1 fade-to-black wipe, before F_WipeStartScreen");
#endif
				F_WipeStartScreen();
				V_DrawFill(0, 0, BASEVIDWIDTH, BASEVIDHEIGHT, 31);
				F_WipeEndScreen();
#ifdef _PS3
				PS3_Mark("MARK W2 fade-to-black wipe, before F_RunWipe");
#endif
				F_RunWipe(wipedefs[wipedefindex], gamestate != GS_TIMEATTACK);
#ifdef _PS3
				PS3_Mark("MARK W3 fade-to-black wipe done");
#endif
			}

			if (gamestate != GS_LEVEL && rendermode != render_none)
			{
				V_SetPaletteLump("PLAYPAL"); // Reset the palette
				R_ReInitColormaps(0, LUMPERROR);
			}

#ifdef _PS3
			PS3_Mark("MARK W4 before the second F_WipeStartScreen");
#endif
			F_WipeStartScreen();
#ifdef _PS3
			PS3_Mark("MARK W5 after the second F_WipeStartScreen");
#endif
		}
		else //dedicated servers
		{
			F_RunWipe(wipedefs[wipedefindex], gamestate != GS_TIMEATTACK);
			wipegamestate = gamestate;
		}
	}

	if (dedicated) //bail out after wipe logic
		return;

#ifdef _PS3
	ps3d("D1 after wipe block, before switch(gamestate)");
#endif

	// do buffered drawing
	switch (gamestate)
	{
		case GS_LEVEL:
			if (!gametic)
				break;
			HU_Erase();
			AM_Drawer();
			break;

		case GS_INTERMISSION:
			Y_IntermissionDrawer();
			HU_Erase();
			HU_Drawer();
			break;

		case GS_VOTING:
			Y_VoteDrawer();
			HU_Erase();
			HU_Drawer();
			break;

		case GS_TIMEATTACK:
			break;

		case GS_INTRO:
#ifdef _PS3
			ps3d("D2a before F_IntroDrawer");
#endif
			F_IntroDrawer();
#ifdef _PS3
			ps3d("D2b after F_IntroDrawer");
#endif
			if (wipegamestate == (gamestate_t)-1)
			{
				wipe = true;
				wipedefindex = gamestate; // wipe_xxx_toblack
			}
			break;

		case GS_CUTSCENE:
			F_CutsceneDrawer();
			HU_Erase();
			HU_Drawer();
			break;

		case GS_GAMEEND:
			F_GameEndDrawer();
			break;

		case GS_EVALUATION:
			F_GameEvaluationDrawer();
			HU_Erase();
			HU_Drawer();
			break;

		case GS_CONTINUING:
			F_ContinueDrawer();
			break;

		case GS_CREDITS:
			F_CreditDrawer();
			HU_Erase();
			HU_Drawer();
			break;

		case GS_TITLESCREEN:
#ifdef _PS3
			ps3d("D2c before F_TitleScreenDrawer");
#endif
			F_TitleScreenDrawer();
#ifdef _PS3
			ps3d("D2d after F_TitleScreenDrawer");
#endif
			if (wipe)
				wipedefindex = wipe_titlescreen_toblack;
			break;

		case GS_WAITINGPLAYERS:
			// The clientconnect drawer is independent...
			if (netgame)
			{
				// I don't think HOM from nothing drawing is independent...
				F_WaitingPlayersDrawer();
				HU_Erase();
				HU_Drawer();
			}
		case GS_DEDICATEDSERVER:
		case GS_NULL:
			break;
	}
#ifdef _PS3
	ps3d("D3 after switch(gamestate)");
#endif

	if (gamestate == GS_LEVEL)
	{
		// draw the view directly
		if (cv_renderview.value && !automapactive)
		{
			R_ApplyLevelInterpolators(R_UsingFrameInterpolation() ? rendertimefrac : FRACUNIT);

			for (i = 0; i <= splitscreen; i++)
			{
				if (players[displayplayers[i]].mo || players[displayplayers[i]].playerstate == PST_DEAD)
				{
					if (i == 0) // Initialize for P1
					{
						viewwindowy = 0;
						viewwindowx = 0;

						topleft = screens[0] + viewwindowy*vid.width + viewwindowx;
						objectsdrawn = 0;
					}

					viewssnum = i;

#ifdef HWRENDER
					if (rendermode != render_soft)
						HWR_RenderPlayerView(i, &players[displayplayers[i]]);
					else
#endif
					if (rendermode != render_none)
					{
						if (i > 0) // Splitscreen-specific
						{
							switch (i)
							{
								case 1:
									if (splitscreen > 1)
									{
										viewwindowx = viewwidth;
										viewwindowy = 0;
									}
									else
									{
										viewwindowx = 0;
										viewwindowy = viewheight;
									}
									M_Memcpy(ylookup, ylookup2, viewheight*sizeof (ylookup[0]));
									break;
								case 2:
									viewwindowx = 0;
									viewwindowy = viewheight;
									M_Memcpy(ylookup, ylookup3, viewheight*sizeof (ylookup[0]));
									break;
								case 3:
									viewwindowx = viewwidth;
									viewwindowy = viewheight;
									M_Memcpy(ylookup, ylookup4, viewheight*sizeof (ylookup[0]));
								default:
									break;
							}


							topleft = screens[0] + viewwindowy*vid.width + viewwindowx;
						}

#ifdef _PS3
						// 2026-08-26 -- bisection knob, temporary. The title
						// screen survives 183s at 60fps with rolling demos
						// off; every failure so far needs GS_LEVEL. Skipping
						// only the 3D view (level load, game logic, HUD and
						// wipes all still run) says whether the software
						// renderer itself is what kills RPCS3.
						if (!ps3_norender3d)
#endif
						R_RenderPlayerView(&players[displayplayers[i]]);

						if (i > 0)
							M_Memcpy(ylookup, ylookup1, viewheight*sizeof (ylookup[0]));
					}
				}
			}

			if (rendermode == render_soft)
			{
				for (i = 0; i <= splitscreen; i++)
				{
					if (postimgtype[i])
						V_DoPostProcessor(i, postimgtype[i], postimgparam[i]);
				}
			}

			R_RestoreLevelInterpolators();
		}

		if (lastdraw)
		{
			if (rendermode == render_soft)
			{
				VID_BlitLinearScreen(screens[0], screens[1], vid.width*vid.bpp, vid.height, vid.width*vid.bpp, vid.rowbytes);
				usebuffer = true;
			}
			lastdraw = false;
		}

		ST_Drawer();
		HU_Drawer();
	}

	// change gamma if needed
	// (GS_LEVEL handles this already due to level-specific palettes)
	if (forcerefresh && gamestate != GS_LEVEL)
		V_SetPalette(0);

	wipegamestate = gamestate;

	// draw pause pic
	if (paused && cv_showhud.value && !demo.playback)
	{
		INT32 py;
		patch_t *patch;
		if (automapactive)
			py = 4;
		else
			py = viewwindowy + 4;
		patch = W_CachePatchName("M_PAUSE", PU_CACHE);
		V_DrawScaledPatch(viewwindowx + (BASEVIDWIDTH - SHORT(patch->width))/2, py, 0, patch);
	}

	if (demo.rewinding)
		V_DrawFadeScreen(TC_RAINBOW, (leveltime & 0x20) ? SKINCOLOR_PASTEL : SKINCOLOR_MOONSLAM);

	// vid size change is now finished if it was on...
	vid.recalc = 0;

#ifdef _PS3
	ps3d("D4 before CON_Drawer");
#endif
	// FIXME: draw either console or menu, not the two
	if (gamestate != GS_TIMEATTACK)
		CON_Drawer();
#ifdef _PS3
	ps3d("D5 after CON_Drawer, before M_Drawer");
#endif

#ifdef HAVE_THREADS
	I_lock_mutex(&m_menu_mutex);
#endif
	M_Drawer(); // menu is drawn even on top of everything
#ifdef HAVE_THREADS
	I_unlock_mutex(m_menu_mutex);
#endif
	// focus lost moved to M_Drawer
#ifdef _PS3
	ps3d("D6 after M_Drawer");
#endif

	//
	// wipe update
	//
	if (wipe)
	{
		// note: moved up here because NetUpdate does input changes
		// and input during wipe tends to mess things up
		wipedefindex += WIPEFINALSHIFT;

		if (rendermode != render_none)
		{
#ifdef _PS3
			ps3d("D7 before F_WipeEndScreen");
			PS3_Mark("MARK W6 wipe update, before F_WipeEndScreen");
#endif
			F_WipeEndScreen();
#ifdef _PS3
			ps3d("D7b after F_WipeEndScreen, before F_RunWipe");
			PS3_Mark("MARK W7 wipe update, before F_RunWipe");
#endif
			F_RunWipe(wipedefs[wipedefindex], gamestate != GS_TIMEATTACK);
#ifdef _PS3
			ps3d("D8 after F_RunWipe");
			PS3_Mark("MARK W8 wipe update done");
#endif
		}
	}

#ifdef _PS3
	ps3d("D9 before NetUpdate");
#endif
	NetUpdate(); // send out any new accumulation
#ifdef _PS3
	ps3d("D10 after NetUpdate");
#endif

	// It's safe to end the game now.
	if (G_GetExitGameFlag())
	{
		Command_ExitGame_f();
		G_ClearExitGameFlag();
	}

	//
	// normal update
	//
	if (!wipe)
	{
		if (cv_netstat.value)
		{
			char s[50];
			Net_GetNetStat();

			s[sizeof s - 1] = '\0';

			snprintf(s, sizeof s - 1, "get %d b/s", getbps);
			V_DrawRightAlignedString(BASEVIDWIDTH, BASEVIDHEIGHT-ST_HEIGHT-40, V_YELLOWMAP, s);
			snprintf(s, sizeof s - 1, "send %d b/s", sendbps);
			V_DrawRightAlignedString(BASEVIDWIDTH, BASEVIDHEIGHT-ST_HEIGHT-30, V_YELLOWMAP, s);
			snprintf(s, sizeof s - 1, "GameMiss %.2f%%", gamelostpercent);
			V_DrawRightAlignedString(BASEVIDWIDTH, BASEVIDHEIGHT-ST_HEIGHT-20, V_YELLOWMAP, s);
			snprintf(s, sizeof s - 1, "SysMiss %.2f%%", lostpercent);
			V_DrawRightAlignedString(BASEVIDWIDTH, BASEVIDHEIGHT-ST_HEIGHT-10, V_YELLOWMAP, s);
		}

		if (cv_shittyscreen.value)
			V_DrawVhsEffect(cv_shittyscreen.value == 2);

#ifdef _PS3
		ps3d("D11 before I_FinishUpdate");
		// the isolation-test burst that used to live here has been superseded:
		// the actual workaround (ps3rsxnudge, interleaved fflush calls between
		// the SDL/RSX sub-calls) now lives permanently inside I_FinishUpdate()
		// itself (sdl/i_video.c) since that's the only configuration that works
#endif
		I_FinishUpdate(); // page flip or blit buffer
#ifdef _PS3
		ps3d("D12 after I_FinishUpdate");
#endif
	}
#ifdef _PS3
	ps3d("D13 D_Display return");
#endif
}

// =========================================================================
// D_SRB2Loop
// =========================================================================

tic_t rendergametic;

#ifdef _PS3
static void ps3m(const char *msg)
{
	FILE *f = fopen(PS3_DebugPath("psdebug2.txt"), "a");
	if (f) { fputs(msg, f); fputc('\n', f); fflush(f); fclose(f); }
}
static void ps3mloop(int iter, const char *step)
{
	FILE *f = fopen(PS3_DebugPath("psdebug9.txt"), "a");
	if (f) { fprintf(f, "F%d %s\n", iter, step); fflush(f); fclose(f); }
}

// ---------------------------------------------------------------------------
// 2026-08-26 -- PS3 wall-clock profiler. MEASUREMENT ONLY: nothing in here
// changes how the game paces itself. Two questions to settle before touching
// any timing code:
//
//  1. Which clock sources on this toolchain actually work? gettimeofday() is
//     suspect: PS3DK's runtime/lv2/librt/gettod.c:19 calls
//     sysGetCurrentTime(ptimeval, ptimezone) -- i.e. it hands the whole
//     struct timeval in as the "sec" out-pointer and NULL (the timezone arg)
//     as the "nsec" out-pointer, so tv_usec is never written. Every fork of
//     the same tree does "tv_sec = sec; tv_usec = nsec/1000;" instead.
//     SDL_GetTicks()/SDL_GetPerformanceCounter() sit on top of that, and so
//     does every tic-pacing wait loop in the game.
//
//  2. How much of a frame goes into the per-frame debug file writes left over
//     from the flip-#555 investigation? There are 8 fopen/fprintf/fflush/
//     fclose cycles per frame here plus 8 more in I_FinishUpdate, all
//     appending to files on the emulated HDD.
//
// Everything is timed on the PPU timebase (mftb), which is independent of
// both suspects.
// ---------------------------------------------------------------------------
#include <sys/systime.h>   // sysGetCurrentTime, sysGetTimebaseFrequency, sysUsleep
#include <sys/time.h>      // gettimeofday
#include <sys/thread.h>    // sysThreadGetStackInformation -- see the stack watermark below
#include <unistd.h>        // usleep

// ---------------------------------------------------------------------------
// 2026-08-26 -- stack watermark.
//
// cdb caught the RPCS3 crash as a host NX fault with RIP = 0: guest code
// branched through a null code pointer. A smashed return address is the
// natural way to get one, and running out of stack is the natural way to get
// that. The suspicion is structural rather than a hunch: TanakaDOOM-cGcm runs
// the same toolchain and the same kind of software renderer on PS3 without
// dying, and the one thing it does not have is SDL -- whose PSL1GHT backend
// hardcodes a 16KB stack for every thread it creates
// (~/SDL2_PSL1GHT/src/thread/psl1ght/SDL_systhread.c:73, "size_t stack_size =
// 0x4000"). SRB2's renderer recurses through R_RenderBSPNode and its thinkers
// call into each other, and "how much stack do we actually use" has never been
// answered on this port.
//
// So measure it. sysThreadGetStackInformation (syscall 49, verified in
// $PS3DEV/ps3dk/ppu/include/sys/thread.h) gives the running thread's stack
// buffer; PS3_StackTouch() keeps the lowest stack pointer ever seen and every
// psdebugS.txt line carries the peak. A compare and a store per call, so it is
// affordable even inside the BSP recursion.
// ---------------------------------------------------------------------------
static u32 ps3stack_base = 0;
static u32 ps3stack_size = 0;
static u32 ps3stack_min = 0xFFFFFFFFu;

static void PS3_StackInit(void)
{
	sys_ppu_thread_stack_t si;

	si.pst_addr = 0;
	si.pst_size = 0;

	if (sysThreadGetStackInformation(&si) == 0)
	{
		ps3stack_base = (u32)(uintptr_t)si.pst_addr;
		ps3stack_size = (u32)si.pst_size;
	}
}

void PS3_StackTouch(void)
{
	u32 sp = (u32)(uintptr_t)__builtin_frame_address(0);

	if (sp < ps3stack_min)
		ps3stack_min = sp;
}

// Same idiom as the toolchain's __gettime() macro in
// $PS3DEV/ps3dk/ppu/include/sys/ppu-asm.h (mftb, retried while it reads 0).
// Written out here rather than including that header, which would also drag
// its bswap static-inline block into this translation unit.
static inline u64 ps3prof_tb(void)
{
	unsigned long long tb;
	__asm__ __volatile__(
		"1:\n\t"
		"mftb  %[t]\n\t"
		"cmpwi 7,%[t],0\n\t"
		"beq-  7,1b"
		: [t] "=r"(tb) : : "cr7");
	return (u64)tb;
}

static u64 ps3prof_tbfreq = 79800000ULL;   // replaced with the real value at probe time
#define PS3PROF_TB2US(d) (((u64)(d)) * 1000000ULL / ps3prof_tbfreq)

#define PS3PROF_FRAMES  500  // main-loop iterations recorded before the dump
#define PS3PROF_WARMUP  200  // frames before this are excluded from the averages
#define PS3PROF_BLOCK   100  // after warmup, traces alternate on/off per block

// The debug writes are A/B'd in interleaved blocks rather than at a single
// split point: the intro plays out inside the first few hundred main-loop
// iterations and is far more expensive per frame than the title screen, so a
// single "on then off" split would price that transition instead of the
// writes.
// Which families of per-frame debug file writes are enabled, as a bitmask.
// Read here and by i_video.c, d_clisrv.c, d_net.c and g_game.c (those use the
// bit values directly, since this is a debug-only switch not worth a header).
//
// Measured 2026-08-26: one fopen/fprintf/fflush/fclose cycle on the emulated
// HDD costs 903us, and the ~16 per frame cost 9.7ms -- 48fps with them all on
// versus 91fps with them all off, over 400 title-screen frames each. So the
// shipping value is 0.
//
// It is a bitmask rather than a flag because these writes turn out to keep the
// game alive: with all of them off RPCS3 segfaults two intro tics in, with all
// of them on the game reaches the title screen. Same signature as the
// ps3rsxnudge note in i_video.c -- interleaved real syscalls between the RSX
// sub-calls mask the fault, while a plain delay does not (four negative
// isolation results on delay alone, 23/08). Enabling one family at a time
// narrows down where the missing serialisation actually is.
#define PS3TRACE_LOOP     1	// ps3mloop, D_SRB2Loop, 8 sites/frame, no RSX nearby
#define PS3TRACE_DISPLAY  2	// ps3d, D_Display, up to 19 sites/frame
#define PS3TRACE_FINISH   4	// ps3fu, I_FinishUpdate, 8 sites/frame, closest to the gcm calls
#define PS3TRACE_LOGIC    8	// ps3cs / ps3n / ps3gt2, game logic, furthest from the RSX
#define PS3TRACE_DISPLAY_SYNC 16	// ps3d sites issue a "sync" barrier instead of writing
#define PS3TRACE_STATE       32	// psdebugS.txt game-state log (cheap, see PS3_StateWatch)
#define PS3TRACE_FIFO        64	// command-FIFO watch in i_video_ps3_gcm.c (cheap, ~30 lines/lap)
#define PS3TRACE_MARK       128	// PS3_Mark() checkpoints on one-shot paths (cheap, ~10 lines)

// Shipping value. DISPLAY_SYNC is a WORKAROUND, not a fix: without some
// serialisation at the ps3d sites the game does not survive two intro tics,
// and nobody has established why. STATE is the psdebugS.txt progress log.
// The file-writing families (LOOP/DISPLAY/FINISH/LOGIC) stay off -- 903us each.
//
// 2026-08-26 ~17:00: FIFO added, and the answer came back negative -- the FIFO
// wraps cleanly every ~250 flips and the crash lands 145 frames off one. Kept
// on because it is nearly free and it dates the wraps on the same timeline.
// ~18:50: MARK added to walk the title-screen -> attract-demo transition.
int ps3_debugtrace = PS3TRACE_DISPLAY_SYNC | PS3TRACE_STATE | PS3TRACE_FIFO | PS3TRACE_MARK;

// 2026-08-26 -- bisection knobs, temporary, NOT shipping options. Set both
// back to 0 once the questions they answer are settled.
//
// ps3_norender3d: skips R_RenderPlayerView, leaving the rest of the level path
// intact. ANSWERED 19:23 -- still died, inside P_SetupLevel, so the software 3D
// renderer is not the culprit.
//
// ps3_noaudio: never opens the audio device, so no SDL audio callback thread
// exists. See the call site in D_SRB2Main for why that is the next suspect.
int ps3_norender3d = 0;
int ps3_noaudio = 0;

static unsigned int ps3prof_total[PS3PROF_FRAMES];
static unsigned int ps3prof_tics[PS3PROF_FRAMES];
static unsigned int ps3prof_disp[PS3PROF_FRAMES];
static unsigned int ps3prof_slp[PS3PROF_FRAMES];
static unsigned char ps3prof_on[PS3PROF_FRAMES];
static int ps3prof_dumped = 0;

static void PS3_ClockProbe(void)
{
	FILE *f;
	int i;
	u64 t0, t1;
	volatile u64 sink = 0;

	ps3prof_tbfreq = sysGetTimebaseFrequency();
	if (ps3prof_tbfreq == 0)
		ps3prof_tbfreq = 79800000ULL;

	f = fopen(PS3_DebugPath("psdebugN.txt"), "a");
	if (!f)
		return;

	fprintf(f, "=== PS3 CLOCK PROBE (build 2026-08-26) ===\n");
	fprintf(f, "sysGetTimebaseFrequency() = %llu Hz\n", (unsigned long long)ps3prof_tbfreq);
	fprintf(f, "I_GetPrecisePrecision()   = %llu\n", (unsigned long long)I_GetPrecisePrecision());

	// -- phase 1: do the clocks move at all, and with what granularity?
	// tv_usec is poisoned before each gettimeofday() call: if 0xDEAD comes
	// back unchanged, the toolchain wrapper never wrote it.
	fprintf(f, "-- phase 1: 20 samples, sysUsleep(16000) between --\n");
	for (i = 0; i < 20; i++)
	{
		struct timeval tv;
		u64 sec = 0, nsec = 0, tb;
		precise_t sdl;

		tb = ps3prof_tb();
		sysGetCurrentTime(&sec, &nsec);
		tv.tv_sec = 0;
		tv.tv_usec = 0xDEAD;
		gettimeofday(&tv, NULL);
		sdl = I_GetPreciseTime();

		fprintf(f, "[%02d] tb=%llu sysCur=%llu.%09llu gtod=%lld.%06lld sdlPerf=%llu\n",
			i, (unsigned long long)tb,
			(unsigned long long)sec, (unsigned long long)nsec,
			(long long)tv.tv_sec, (long long)tv.tv_usec,
			(unsigned long long)sdl);

		sysUsleep(16000);
	}

	// -- phase 2: what does a sleep actually cost, measured on the timebase?
	fprintf(f, "-- phase 2: sleep accuracy on the PPU timebase --\n");
	t0 = ps3prof_tb(); sysUsleep(1000);  t1 = ps3prof_tb();
	fprintf(f, "sysUsleep(1000)  -> %llu us\n", (unsigned long long)PS3PROF_TB2US(t1 - t0));
	t0 = ps3prof_tb(); sysUsleep(1000);  t1 = ps3prof_tb();
	fprintf(f, "sysUsleep(1000)  -> %llu us\n", (unsigned long long)PS3PROF_TB2US(t1 - t0));
	t0 = ps3prof_tb(); sysUsleep(16000); t1 = ps3prof_tb();
	fprintf(f, "sysUsleep(16000) -> %llu us\n", (unsigned long long)PS3PROF_TB2US(t1 - t0));
	t0 = ps3prof_tb(); usleep(16000);    t1 = ps3prof_tb();
	fprintf(f, "usleep(16000)    -> %llu us\n", (unsigned long long)PS3PROF_TB2US(t1 - t0));
	t0 = ps3prof_tb(); I_Sleep(1);       t1 = ps3prof_tb();
	fprintf(f, "I_Sleep(1)       -> %llu us\n", (unsigned long long)PS3PROF_TB2US(t1 - t0));
	t0 = ps3prof_tb(); I_Sleep(1);       t1 = ps3prof_tb();
	fprintf(f, "I_Sleep(1)       -> %llu us\n", (unsigned long long)PS3PROF_TB2US(t1 - t0));

	// -- phase 3: unit cost of the things called in the inner loops
	fprintf(f, "-- phase 3: unit costs --\n");
	t0 = ps3prof_tb();
	for (i = 0; i < 1000; i++)
		sink += ps3prof_tb();
	t1 = ps3prof_tb();
	fprintf(f, "1000x mftb              -> %llu us\n", (unsigned long long)PS3PROF_TB2US(t1 - t0));

	t0 = ps3prof_tb();
	for (i = 0; i < 1000; i++)
	{
		u64 s = 0, n = 0;
		sysGetCurrentTime(&s, &n);
		sink += s + n;
	}
	t1 = ps3prof_tb();
	fprintf(f, "1000x sysGetCurrentTime -> %llu us\n", (unsigned long long)PS3PROF_TB2US(t1 - t0));

	t0 = ps3prof_tb();
	for (i = 0; i < 1000; i++)
		sink += I_GetPreciseTime();
	t1 = ps3prof_tb();
	fprintf(f, "1000x I_GetPreciseTime  -> %llu us\n", (unsigned long long)PS3PROF_TB2US(t1 - t0));

	t0 = ps3prof_tb();
	for (i = 0; i < 20; i++)
		ps3mloop(0, "clockprobe write-cost sample");
	t1 = ps3prof_tb();
	fprintf(f, "20x debug trace write   -> %llu us total, %llu us each\n",
		(unsigned long long)PS3PROF_TB2US(t1 - t0),
		(unsigned long long)(PS3PROF_TB2US(t1 - t0) / 20));

	fprintf(f, "=== end of clock probe (sink=%llu) ===\n", (unsigned long long)sink);
	fflush(f);
	fclose(f);
}

// Averages every recorded frame in [lo,hi) whose trace flag matches "want".
static void PS3_ProfMean(FILE *f, const char *label, int lo, int hi, int want)
{
	u64 st = 0, sk = 0, sd = 0, ss = 0;
	unsigned long long avg, fps_x100;
	int i, n = 0;

	for (i = lo; i < hi && i < PS3PROF_FRAMES; i++)
	{
		if (ps3prof_on[i] != (unsigned char)want)
			continue;
		st += ps3prof_total[i];
		sk += ps3prof_tics[i];
		sd += ps3prof_disp[i];
		ss += ps3prof_slp[i];
		n++;
	}
	if (n == 0)
		return;

	avg = (unsigned long long)(st / n);
	fps_x100 = avg ? (100000000ULL / avg) : 0;
	fprintf(f, "%-18s n=%4d  total=%8llu us (%llu.%02llu fps)  TryRunTics=%8llu  D_Display=%8llu  sleepblock=%8llu\n",
		label, n, avg, fps_x100 / 100, fps_x100 % 100,
		(unsigned long long)(sk / n), (unsigned long long)(sd / n),
		(unsigned long long)(ss / n));
}

static void PS3_ProfDump(void)
{
	FILE *f = fopen(PS3_DebugPath("psdebugO.txt"), "a");
	int i;

	if (!f)
		return;

	fprintf(f, "=== PS3 FRAME PROFILE (build 2026-08-26), tbfreq=%llu ===\n",
		(unsigned long long)ps3prof_tbfreq);
	fprintf(f, "columns: iteration, trace state, total us, TryRunTics us, D_Display us, sleepblock us\n");
	for (i = 0; i < PS3PROF_FRAMES; i++)
		fprintf(f, "F%04d %s %9u %9u %9u %9u\n", i + 1,
			ps3prof_on[i] ? "trace-ON " : "trace-OFF",
			ps3prof_total[i], ps3prof_tics[i], ps3prof_disp[i], ps3prof_slp[i]);
	fprintf(f, "--- averages, warmup frames 1-%d excluded ---\n", PS3PROF_WARMUP);
	PS3_ProfMean(f, "debug traces ON",  PS3PROF_WARMUP, PS3PROF_FRAMES, 1);
	PS3_ProfMean(f, "debug traces OFF", PS3PROF_WARMUP, PS3PROF_FRAMES, 0);
	fflush(f);
	fclose(f);
}


// ---------------------------------------------------------------------------
// 2026-08-26 -- game state log, psdebugS.txt.
//
// Written only when something actually changes, plus one heartbeat per second.
// A debug write costs 903us on the emulated HDD (measured), so a per-frame log
// would eat 5% of a 60Hz frame budget; at roughly one line per second the cost
// is about 0.09%. Every line is flushed and the file closed, so the last line
// written survives an RPCS3 host segfault -- which is the point, given the
// crash currently under investigation takes the whole emulator down.
//
// Gives a readable trail (loading -> intro -> title screen -> demo -> level)
// without needing screenshots, which do not work on a locked desktop anyway.
// ---------------------------------------------------------------------------
static const char *PS3_GameStateName(gamestate_t gs)
{
	switch (gs)
	{
		case GS_NULL:            return "GS_NULL";
		case GS_LEVEL:           return "GS_LEVEL";
		case GS_INTERMISSION:    return "GS_INTERMISSION";
		case GS_VOTING:          return "GS_VOTING";
		case GS_CONTINUING:      return "GS_CONTINUING";
		case GS_TITLESCREEN:     return "GS_TITLESCREEN";
		case GS_TIMEATTACK:      return "GS_TIMEATTACK";
		case GS_CREDITS:         return "GS_CREDITS";
		case GS_EVALUATION:      return "GS_EVALUATION";
		case GS_GAMEEND:         return "GS_GAMEEND";
		case GS_INTRO:           return "GS_INTRO";
		case GS_CUTSCENE:        return "GS_CUTSCENE";
		case GS_DEDICATEDSERVER: return "GS_DEDICATEDSERVER";
		case GS_WAITINGPLAYERS:  return "GS_WAITINGPLAYERS";
		default:                 return "GS_unknown";
	}
}

static const char *PS3_GameActionName(gameaction_t ga)
{
	switch (ga)
	{
		case ga_nothing:   return "ga_nothing";
		case ga_completed: return "ga_completed";
		case ga_worlddone: return "ga_worlddone";
		case ga_startcont: return "ga_startcont";
		case ga_continued: return "ga_continued";
		case ga_startvote: return "ga_startvote";
		default:           return "ga_unknown";
	}
}

static u64 ps3state_epoch_tb = 0;

static void PS3_StateLine(u64 now_us, unsigned int frame, unsigned int frame_us, const char *what)
{
	FILE *f = fopen(PS3_DebugPath("psdebugS.txt"), "a");
	unsigned int fps_x100;

	if (!f)
		return;

	fps_x100 = frame_us ? (unsigned int)(100000000UL / frame_us) : 0;

	fprintf(f, "[%4llu.%03llus f%-6u tic%-7u %3u.%02u fps] %s\n",
		(unsigned long long)(now_us / 1000000ULL),
		(unsigned long long)((now_us / 1000ULL) % 1000ULL),
		frame, (unsigned int)gametic,
		fps_x100 / 100, fps_x100 % 100,
		what);

	// Stack watermark on the same line: how deep we have ever gone, and how
	// much room was left at that point. If "left" trends towards zero, the
	// null-code-pointer crash is stack exhaustion and we are done guessing.
	if (ps3stack_size != 0)
	{
		u32 top = ps3stack_base + ps3stack_size;
		u32 sp = (u32)(uintptr_t)__builtin_frame_address(0);
		u32 peak = (ps3stack_min == 0xFFFFFFFFu) ? sp : ps3stack_min;

		fprintf(f, "        stack base=%08x size=%u  now=%u  PEAK=%u  left_at_peak=%d\n",
			(unsigned)ps3stack_base, (unsigned)ps3stack_size,
			(unsigned)(top - sp), (unsigned)(top - peak),
			(int)(peak - ps3stack_base));
	}

	fflush(f);
	fclose(f);
}

// 2026-08-26 -- one-off checkpoint on the same psdebugS.txt timeline.
//
// For tracing a path that runs once, where a per-frame trace family would be
// both too expensive and too noisy. Written for the title-screen -> attract
// demo transition, which three runs have now pinned as the place RPCS3 dies:
// the last heartbeat is always tic 736, and the demo starts at tic 770.
//
// Gated by PS3TRACE_MARK so it costs nothing when off, and it is on a
// once-per-transition path rather than a per-frame one, so the 903us a debug
// write costs is affordable here in a way it is not in D_Display.
static unsigned int ps3state_frame = 0;
static unsigned int ps3state_frame_us = 0;

// ---------------------------------------------------------------------------
// 2026-08-26 -- indirect action-call guard.
//
// The crash signature is a host NX fault at RIP = 0 on the PPU thread: guest
// code jumping through a bad code pointer. Everything else is now excluded --
// the stack peaks at 9312 bytes of 1MB, the zone heap validates clean at every
// phase of P_SetupLevel, and states[] is intact in the linked binary.
//
// So look at the places that actually jump through a pointer without checking
// it. SRB2 has eight, all on the level/gameplay path, and four of them index
// states[] with a number that comes from state data rather than from code
// (A_DualAction, A_RemoteAction and friends read it out of var1/var2).
//
// This reports the offending target and skips the call instead of taking it.
// Three possible outcomes, all of them useful: lines appear and name the site;
// the crash disappears, which proves it; or nothing appears and all eight
// sites are cleared.
//
// The image is at 0x10230 (.text) through 0x39c704 (end of .opd), so a real
// function pointer is 4-byte aligned and inside [0x10000, 0x3a0000).
#define PS3_CODE_LO 0x00010000u
#define PS3_CODE_HI 0x003a0000u

// 2026-08-27 -- the same pointer sanity as PS3_BadAction, minus the state
// number, for indirect calls that are not state actions. P_RunThinkers is the
// one that matters: thinker_t.function.acp1 is called directly for every live
// object every tic, and it was the last unguarded indirect call in the game.
int PS3_BadFunc(const char *where, void *fn)
{
	static int reported = 0;
	u32 a = (u32)(uintptr_t)fn;
	const char *why = NULL;
	char line[192];

	if (fn == NULL)
		why = "NULL function";
	else if ((a & 3u) != 0u)
		why = "misaligned function pointer";
	else if (a < PS3_CODE_LO || a >= PS3_CODE_HI)
		why = "function pointer outside the image";

	if (why == NULL)
		return 0;

	if (reported < 24)
	{
		reported++;
		snprintf(line, sizeof line, "*** BAD CALL *** %s: fn=%08x -- %s (skipped)",
			where, (unsigned)a, why);
		PS3_Mark(line);
		fprintf(stderr, "[PS3] %s\n", line);
	}

	return 1;
}

int PS3_BadAction(const char *where, INT32 statenum, void *fn)
{
	static int reported = 0;
	u32 a = (u32)(uintptr_t)fn;
	const char *why = NULL;
	char line[192];

	if (statenum < 0 || statenum >= NUMSTATES)
		why = "state number out of range";
	else if (fn == NULL)
		why = "NULL action";
	else if ((a & 3u) != 0u)
		why = "misaligned action pointer";
	else if (a < PS3_CODE_LO || a >= PS3_CODE_HI)
		why = "action pointer outside the image";

	if (why == NULL)
		return 0;

	if (reported < 24)
	{
		reported++;
		snprintf(line, sizeof line, "*** BAD ACTION CALL *** %s: state=%d fn=%08x -- %s (skipped)",
			where, (int)statenum, (unsigned)a, why);
		PS3_Mark(line);
		fprintf(stderr, "[PS3] %s\n", line);
	}

	return 1;
}

// 2026-08-26 -- debug files follow srb2home instead of a hardcoded path.
// D_Home() now points at the package USRDIR when the title is installed, so
// on real hardware these land next to the game instead of failing to open in
// a directory that does not exist. Returns a rotating set of static buffers
// so a caller can hold two paths at once without surprises.
const char *PS3_DebugPath(const char *name)
{
	static char buf[4][320];
	static int slot = 0;
	char *out;

	slot = (slot + 1) & 3;
	out = buf[slot];

	// srb2home keeps its "." default until D_SRB2Main reaches the config
	// section, and the earliest traces run before that -- i_main.c writes
	// "M1 before D_SRB2Main" already. Under RPCS3 a relative path landed in
	// the right place anyway, because the emulator's working directory is the
	// EBOOT's own directory; launched from a real XMB it is not, so those
	// traces were silently lost. They are exactly the ones worth having when a
	// boot fails early, which is what a first hardware test tends to do.
	if (srb2home[0] == '\0' || (srb2home[0] == '.' && srb2home[1] == '\0'))
	{
		snprintf(out, sizeof buf[0], "%s/%s", PS3_INSTALLDIR, name);
		return out;
	}

	snprintf(out, sizeof buf[0], "%s%s%s", srb2home,
		(srb2home[0] && srb2home[strlen(srb2home) - 1] == '/') ? "" : "/", name);
	return out;
}

void PS3_Mark(const char *what)
{
	u64 now_us;

	if (!(ps3_debugtrace & PS3TRACE_MARK))
		return;

	if (ps3state_epoch_tb == 0)
		ps3state_epoch_tb = ps3prof_tb();
	now_us = PS3PROF_TB2US(ps3prof_tb() - ps3state_epoch_tb);

	PS3_StateLine(now_us, ps3state_frame, ps3state_frame_us, what);
}

static void PS3_StateWatch(unsigned int frame, unsigned int frame_us)
{
	static int started = 0;
	static gamestate_t last_gs;
	static gameaction_t last_ga;
	static int last_demo;
	static INT16 last_map;
	static u64 next_beat_us;
	char line[192];
	u64 now_us;

	ps3state_frame = frame;
	ps3state_frame_us = frame_us;

	if (!(ps3_debugtrace & PS3TRACE_STATE))
		return;

	if (ps3state_epoch_tb == 0)
		ps3state_epoch_tb = ps3prof_tb();
	now_us = PS3PROF_TB2US(ps3prof_tb() - ps3state_epoch_tb);

	if (!started)
	{
		started = 1;
		PS3_StackInit();
		last_gs = gamestate;
		last_ga = gameaction;
		last_demo = demo.playback ? 1 : 0;
		last_map = gamemap;
		next_beat_us = now_us;
		snprintf(line, sizeof line, "start   gamestate=%s gamemap=%d",
			PS3_GameStateName(gamestate), (int)gamemap);
		PS3_StateLine(now_us, frame, frame_us, line);
		return;
	}

	if (gamestate != last_gs)
	{
		snprintf(line, sizeof line, "gamestate  %s -> %s",
			PS3_GameStateName(last_gs), PS3_GameStateName(gamestate));
		PS3_StateLine(now_us, frame, frame_us, line);
		last_gs = gamestate;
	}

	if (gameaction != last_ga)
	{
		snprintf(line, sizeof line, "gameaction %s -> %s",
			PS3_GameActionName(last_ga), PS3_GameActionName(gameaction));
		PS3_StateLine(now_us, frame, frame_us, line);
		last_ga = gameaction;
	}

	if ((demo.playback ? 1 : 0) != last_demo)
	{
		last_demo = demo.playback ? 1 : 0;
		snprintf(line, sizeof line, "demo playback %s", last_demo ? "STARTED" : "stopped");
		PS3_StateLine(now_us, frame, frame_us, line);
	}

	if (gamemap != last_map)
	{
		snprintf(line, sizeof line, "gamemap %d -> %d", (int)last_map, (int)gamemap);
		PS3_StateLine(now_us, frame, frame_us, line);
		last_map = gamemap;
	}

	if (now_us >= next_beat_us)
	{
		next_beat_us = now_us + 1000000ULL;	// one line per second
		snprintf(line, sizeof line, "heartbeat  %s%s",
			PS3_GameStateName(gamestate), demo.playback ? " (demo)" : "");
		PS3_StateLine(now_us, frame, frame_us, line);

		// Once a second, validate the whole zone heap. GS_LEVEL is one of the
		// three places RPCS3 has died, so the level-load probes in
		// P_SetupLevel are not enough on their own.
		PS3_HeapProbe("heartbeat");
	}
}

static void PS3_ProfRecord(int iter, unsigned int total, unsigned int tics,
	unsigned int disp, unsigned int slp)
{
	int i;

	if (iter < 1 || iter > PS3PROF_FRAMES)
		return;

	i = iter - 1;
	ps3prof_total[i] = total;
	ps3prof_tics[i] = tics;
	ps3prof_disp[i] = disp;
	ps3prof_slp[i] = slp;
	ps3prof_on[i] = (unsigned char)(ps3_debugtrace ? 1 : 0);

	if (iter == PS3PROF_FRAMES && !ps3prof_dumped)
	{
		ps3prof_dumped = 1;
		PS3_ProfDump();
	}
}
#else
#define ps3m(msg)
#endif

void D_SRB2Loop(void)
{
	tic_t entertic = 0, oldentertics = 0, realtics = 0, rendertimeout = INFTICS;
	double deltatics = 0.0;
	double deltasecs = 0.0;

	boolean interp = false;
	boolean doDisplay = false;

	if (dedicated)
		server = true;

	// Pushing of + parameters is now done back in D_SRB2Main, not here.

#ifdef _WINDOWS
	CONS_Printf("I_StartupMouse()...\n");
	I_DoStartupMouse();
#endif

	I_UpdateTime(cv_timescale.value);
	oldentertics = I_GetTime();

	// end of loading screen: CONS_Printf() will no more call FinishUpdate()
	con_startup = false;

	// make sure to do a d_display to init mode _before_ load a level
	ps3m("L1 before SCR_SetMode");
	SCR_SetMode(); // change video mode
	ps3m("L2 after SCR_SetMode, before SCR_Recalc");
	SCR_Recalc();
	ps3m("L3 after SCR_Recalc");

	// Check and print which version is executed.
	// Use this as the border between setup and the main game loop being entered.
	CONS_Printf(
	"===========================================================================\n"
	"                   We hope you enjoy this game as\n"
	"                     much as we did making it!\n"
	"===========================================================================\n");

	// hack to start on a nice clear console screen.
	COM_ImmedExecute("cls;version");

	ps3m("L4 before KARTKREW patch draw");
	if (rendermode == render_soft)
	{
		ps3m("L5 before W_GetNumForName(KARTKREW)");
		{
			lumpnum_t kklump = W_GetNumForName("KARTKREW");
			ps3m("L6 before W_CacheLumpNum(KARTKREW)");
			{
				patch_t *kkpatch = (patch_t *)W_CacheLumpNum(kklump, PU_CACHE);
				ps3m("L7 before V_DrawFixedPatch");
				V_DrawFixedPatch(0, 0, FRACUNIT/2, 0, kkpatch, NULL);
				ps3m("L8 after V_DrawFixedPatch");
			}
		}
	}
	ps3m("L9 before I_FinishUpdate");
	I_FinishUpdate(); // page flip or blit buffer
	ps3m("L10 after I_FinishUpdate, before main loop");

	for (;;)
	{
		// capbudget is the minimum precise_t duration of a single loop iteration
		precise_t capbudget;
		precise_t enterprecise = I_GetPreciseTime();
		precise_t finishprecise = enterprecise;
#ifdef _PS3
		static int ps3loopiter = 0;
		boolean ps3trace;
		u64 ps3p_iter0, ps3p_a = 0, ps3p_b = 0;
		unsigned int ps3p_tics = 0, ps3p_disp = 0, ps3p_slp = 0;
		ps3loopiter++;
		ps3p_iter0 = ps3prof_tb();
		// The alternating on/off A/B that used to live here has served its
		// purpose (9.7ms per frame, 48fps vs 91fps) -- ps3_debugtrace now just
		// stays at whatever it is initialised to, off by default.
		ps3trace = ((ps3_debugtrace & PS3TRACE_LOOP) && ps3loopiter <= 3000);
		if (ps3loopiter == 1) { ps3m("L11 first main loop iteration entered"); PS3_ClockProbe(); }
		if (ps3trace) ps3mloop(ps3loopiter, "top of iteration");
#endif

		{
			// Casting the return value of a function is bad practice (apparently)
			double budget = round((1.0 / R_GetFramerateCap()) * I_GetPrecisePrecision());
			capbudget = (precise_t) budget;
		}

		I_UpdateTime(cv_timescale.value);

		if (lastwipetic)
		{
			oldentertics = lastwipetic;
			lastwipetic = 0;
		}

		// get real tics
		entertic = I_GetTime();
		realtics = entertic - oldentertics;
		oldentertics = entertic;
#ifdef _PS3
		if (realtics != 0) ps3mloop(ps3loopiter, va("RT realtics=%lu entertic=%lu", (unsigned long)realtics, (unsigned long)entertic));
#endif

		if (demo.playback && gamestate == GS_LEVEL)
		{
			// Nicer place to put this.
			realtics = realtics * cv_playbackspeed.value;
		}

#ifdef DEBUGFILE
		if (!realtics)
			if (debugload)
				debugload--;
#endif

		interp = R_UsingFrameInterpolation() && !dedicated;
		doDisplay = false;

#ifdef HW3SOUND
		HW3S_BeginFrameUpdate();
#endif

		refreshdirmenu = 0; // not sure where to put this, here as good as any?

		if (realtics > 0 || singletics)
		{
			// don't skip more than 10 frames at a time
			// (fadein / fadeout cause massive frame skip!)
			if (realtics > 8)
				realtics = 1;

			// process tics (but maybe not if realtic == 0)
#ifdef _PS3
			ps3p_a = ps3prof_tb();
#endif
			TryRunTics(realtics);
#ifdef _PS3
			ps3p_b = ps3prof_tb();
			ps3p_tics = (unsigned int)PS3PROF_TB2US(ps3p_b - ps3p_a);
			if (ps3trace) ps3mloop(ps3loopiter, "after TryRunTics");
#endif

			if (lastdraw || singletics || gametic > rendergametic)
			{
				rendergametic = gametic;
				rendertimeout = entertic + TICRATE/17;

				doDisplay = true;
			}
			else if (rendertimeout < entertic) // in case the server hang or netsplit
			{
				doDisplay = true;
			}

			renderisnewtic = true;
		}
		else
		{
			renderisnewtic = false;
		}

		if (interp)
		{
			renderdeltatics = FLOAT_TO_FIXED(deltatics);

			if (!(paused || P_AutoPause()) && deltatics < 1.0 && !hu_stopped)
			{
				rendertimefrac = g_time.timefrac;
			}
			else
			{
				rendertimefrac = FRACUNIT;
			}
		}
		else
		{
			renderdeltatics = realtics * FRACUNIT;
			rendertimefrac = FRACUNIT;
		}

		if (interp || doDisplay)
		{
#ifdef _PS3
			if (ps3trace) ps3mloop(ps3loopiter, "before D_Display");
			ps3p_a = ps3prof_tb();
#endif
			D_Display();
#ifdef _PS3
			ps3p_b = ps3prof_tb();
			ps3p_disp = (unsigned int)PS3PROF_TB2US(ps3p_b - ps3p_a);
			if (ps3trace) ps3mloop(ps3loopiter, "after D_Display");
#endif
		}

		// Only take screenshots after drawing.
		if (moviemode)
			M_SaveFrame();
		if (takescreenshot)
			M_DoScreenShot();

		// consoleplayer -> displayplayers (hear sounds from viewpoint)
		S_UpdateSounds(); // move positional sounds
#ifdef _PS3
		if (ps3trace) ps3mloop(ps3loopiter, "after S_UpdateSounds");
#endif

		// check for media change, loop music..
		I_UpdateCD();
#ifdef _PS3
		if (ps3trace) ps3mloop(ps3loopiter, "after I_UpdateCD");
#endif

#ifdef HW3SOUND
		HW3S_EndFrameUpdate();
#endif

#ifdef HAVE_BLUA
		LUA_Step();
#endif

#ifdef HAVE_DISCORDRPC
		if (! dedicated)
		{
			Discord_RunCallbacks();
		}
#endif

		// Fully completed frame made.
#ifdef _PS3
		ps3p_a = ps3prof_tb();
#endif
		finishprecise = I_GetPreciseTime();
		if (!singletics)
		{
			INT64 elapsed = (INT64)(finishprecise - enterprecise);

			// in the case of "match refresh rate" + vsync, don't sleep at all
			const boolean vsync_with_match_refresh = cv_vidwait.value && cv_fpscap.value == 0;

			if (elapsed > 0 && (INT64)capbudget > elapsed && !vsync_with_match_refresh)
			{
				I_SleepDuration(capbudget - (finishprecise - enterprecise));
			}
		}
#ifdef _PS3
		ps3p_b = ps3prof_tb();
		ps3p_slp = (unsigned int)PS3PROF_TB2US(ps3p_b - ps3p_a);
#endif
		// Capture the time once more to get the real delta time.
		finishprecise = I_GetPreciseTime();
		deltasecs = (double)((INT64)(finishprecise - enterprecise)) / I_GetPrecisePrecision();
		deltatics = deltasecs * NEWTICRATE;
#ifdef _PS3
		if (ps3trace) ps3mloop(ps3loopiter, "end of iteration");
		{
			unsigned int ps3p_total = (unsigned int)PS3PROF_TB2US(ps3prof_tb() - ps3p_iter0);

			PS3_ProfRecord(ps3loopiter, ps3p_total, ps3p_tics, ps3p_disp, ps3p_slp);
			PS3_StateWatch((unsigned int)ps3loopiter, ps3p_total);
		}
#endif
	}
}

// =========================================================================
// D_SRB2Main
// =========================================================================

//
// D_StartTitle
//
void D_StartTitle(void)
{
	INT32 i;
	if (netgame)
	{
		if (gametype == GT_RACE) // SRB2kart
		{
			G_SetGamestate(GS_WAITINGPLAYERS); // hack to prevent a command repeat

			if (server)
			{
				char mapname[6];

				strlcpy(mapname, G_BuildMapName(spstage_start), sizeof (mapname));
				strlwr(mapname);
				mapname[5] = '\0';

				COM_BufAddText(va("map %s\n", mapname));
			}
		}

		return;
	}

	// okay, stop now
	// (otherwise the game still thinks we're playing!)
	SV_StopServer();
	SV_ResetServer();

	for (i = 0; i < MAXPLAYERS; i++)
		CL_ClearPlayer(i);

	splitscreen = 0;
	SplitScreen_OnChange();
	botingame = false;
	botskin = 0;
	cv_debug = 0;
	emeralds = 0;

	// In case someone exits out at the same time they start a time attack run,
	// reset modeattacking
	modeattacking = ATTACKING_NONE;

	// empty maptol so mario/etc sounds don't play in sound test when they shouldn't
	maptol = 0;

	gameaction = ga_nothing;
	memset(displayplayers, 0, sizeof(displayplayers));
	consoleplayer = 0;
	//demosequence = -1;
	gametype = GT_RACE; // SRB2kart
	paused = false;
	F_StartTitleScreen();

	// Reset the palette -- SRB2Kart: actually never mind let's do this in the middle of every fade
	/*if (rendermode != render_none)
		V_SetPaletteLump("PLAYPAL");*/
}

//
// D_AddFile
//
static void D_AddFile(const char *file, char **filearray)
{
	size_t pnumwadfiles;
	char *newfile;

	for (pnumwadfiles = 0; filearray[pnumwadfiles]; pnumwadfiles++)
		;

	newfile = malloc(strlen(file) + 1);
	if (!newfile)
	{
		I_Error("No more free memory to AddFile %s",file);
	}
	strcpy(newfile, file);

	filearray[pnumwadfiles] = newfile;
}

static inline void D_CleanFile(char **filearray)
{
	size_t pnumwadfiles;
	for (pnumwadfiles = 0; filearray[pnumwadfiles]; pnumwadfiles++)
	{
		free(filearray[pnumwadfiles]);
		filearray[pnumwadfiles] = NULL;
	}
}

// ==========================================================================
// Identify the SRB2 version, and IWAD file to use.
// ==========================================================================

static boolean AddIWAD(void)
{
	char * path = va(pandf,srb2path,"srb2.srb");

	if (FIL_ReadFileOK(path))
	{
		D_AddFile(path, startupwadfiles);
		return true;
	}
	else
	{
		return false;
	}
}

static void IdentifyVersion(void)
{
	const char *srb2waddir = NULL;

#if (defined (__unix__) && !defined (MSDOS)) || defined (UNIXCOMMON) || defined (HAVE_SDL)
	// change to the directory where 'srb2.srb' is found
	srb2waddir = I_LocateWad();
#endif

	// get the current directory (possible problem on NT with "." as current dir)
	if (srb2waddir)
	{
		strlcpy(srb2path,srb2waddir,sizeof (srb2path));
	}
	else
	{
#if !defined(_WIN32_WCE) && !defined(_PS3)
		if (getcwd(srb2path, 256) != NULL)
			srb2waddir = srb2path;
		else
#endif
		{
#ifdef _arch_dreamcast
			srb2waddir = "/cd";
#else
			srb2waddir = srb2path;
#endif
		}
	}

	// Load the IWAD
	if (! AddIWAD())
	{
		I_Error("SRB2.SRB not found! Expected in %s\n", srb2waddir);
	}

	// will be overwritten in case of -cdrom or unix/win home
	snprintf(configfile, sizeof configfile, "%s" PATHSEP CONFIGFILENAME, srb2waddir);
	configfile[sizeof configfile - 1] = '\0';

	// if you change the ordering of this or add/remove a file, be sure to update the md5
	// checking in D_SRB2Main

#ifdef USE_PATCH_DTA
	// Add our crappy patches to fix our bugs
	D_AddFile(va(pandf,srb2waddir,"patch.dta"));
#endif

	D_AddFile(va(pandf,srb2waddir,"gfx.kart"), startupwadfiles);
	D_AddFile(va(pandf,srb2waddir,"textures.kart"), startupwadfiles);
	D_AddFile(va(pandf,srb2waddir,"chars.kart"), startupwadfiles);
	D_AddFile(va(pandf,srb2waddir,"maps.kart"), startupwadfiles);
#ifdef USE_PATCH_KART
	D_AddFile(va(pandf,srb2waddir,"patch.kart"), startupwadfiles);
#endif

#if !defined (HAVE_SDL) || defined (HAVE_MIXER)
#define MUSICTEST(str) \
	{\
		const char *musicpath = va(pandf,srb2waddir,str);\
		int ms = W_VerifyNMUSlumps(musicpath); \
		if (ms == 1) \
			D_AddFile(musicpath, startupwadfiles); \
		else if (ms == 0) \
			I_Error("File "str" has been modified with non-music/sound lumps"); \
	}
	MUSICTEST("sounds.kart")
	MUSICTEST("music.kart")
#undef MUSICTEST
#endif
}

/* ======================================================================== */
// Just print the nice red titlebar like the original SRB2 for DOS.
/* ======================================================================== */
#ifdef PC_DOS
static inline void D_Titlebar(char *title1, char *title2)
{
	// SRB2 banner
	clrscr();
	textattr((BLUE<<4)+WHITE);
	clreol();
	cputs(title1);

	// standard srb2 banner
	textattr((RED<<4)+WHITE);
	clreol();
	gotoxy((80-strlen(title2))/2, 2);
	cputs(title2);
	normvideo();
	gotoxy(1,3);
}
#endif

//
// Center the title string, then add the date and time of compilation.
//
static inline void D_MakeTitleString(char *s)
{
	char temp[82];
	char *t;
	const char *u;
	INT32 i;

	for (i = 0, t = temp; i < 82; i++)
		*t++=' ';

	for (t = temp + (80-strlen(s))/2, u = s; *u != '\0' ;)
		*t++ = *u++;

	u = compdate;
	for (t = temp + 1, i = 11; i-- ;)
		*t++ = *u++;
	u = comptime;
	for (t = temp + 71, i = 8; i-- ;)
		*t++ = *u++;

	temp[80] = '\0';
	strcpy(s, temp);
}

//
// D_SRB2Main
//
void D_SRB2Main(void)
{
	INT32 p, i;
	char srb2[82]; // srb2 title banner
	char title[82];
	lumpinfo_t *lumpinfo;
	UINT16 wadnum;
	char *name;

	INT32 pstartmap = 1;
	boolean autostart = false;

	// Print GPL notice for our console users (Linux)
	CONS_Printf(
	"\n\nSonic Robo Blast 2 Kart\n"
	"Copyright (C) 1998-2022 by Kart Krew & STJr\n\n"
	"This program comes with ABSOLUTELY NO WARRANTY.\n\n"
	"This is free software, and you are welcome to redistribute it\n"
	"and/or modify it under the terms of the GNU General Public License\n"
	"as published by the Free Software Foundation; either version 2 of\n"
	"the License, or (at your option) any later version.\n"
	"See the 'LICENSE.txt' file for details.\n\n"
	"Sonic the Hedgehog and related characters are trademarks of SEGA.\n"
	"We do not claim ownership of SEGA's intellectual property used\n"
	"in this program.\n\n");

	// keep error messages until the final flush(stderr)
#if !defined (PC_DOS) && !defined (_WIN32_WCE) && !defined(NOTERMIOS)
	if (setvbuf(stderr, NULL, _IOFBF, 1000))
		I_OutputMsg("setvbuf didnt work\n");
#endif

#ifdef GETTEXT
	// initialise locale code
	M_StartupLocale();
#endif

	// get parameters from a response file (eg: srb2 @parms.txt)
	M_FindResponseFile();

	// MAINCFG is now taken care of where "OBJCTCFG" is handled
	G_LoadGameSettings();

	// Test Dehacked lists
	DEH_Check();

	// identify the main IWAD file to use
	IdentifyVersion();

#if !defined (_WIN32_WCE) && !defined(NOTERMIOS)
	setbuf(stdout, NULL); // non-buffered output
#endif

#if defined (_WIN32_WCE) //|| defined (_DEBUG) || defined (GP2X)
	devparm = M_CheckParm("-nodebug") == 0;
#else
	devparm = M_CheckParm("-debug") != 0;
#endif

	// for dedicated server
#if !defined (_WINDOWS) //already check in win_main.c
	dedicated = M_CheckParm("-dedicated") != 0;
#endif

	strcpy(title, "SRB2Kart");
	strcpy(srb2, "SRB2Kart");
	D_MakeTitleString(srb2);

#ifdef PC_DOS
	D_Titlebar(srb2, title);
#endif

#if defined (__OS2__) && !defined (HAVE_SDL)
	// set PM window title
	snprintf(pmData->title, sizeof (pmData->title),
		"SRB2Kart" VERSIONSTRING ": %s",
		title);
	pmData->title[sizeof (pmData->title) - 1] = '\0';
#endif

	if (devparm)
		CONS_Printf(M_GetText("Development mode ON.\n"));

	// default savegame
	strcpy(savegamename, SAVEGAMENAME"%u.ssg");

	{
		const char *userhome = D_Home(); //Alam: path to home
		FILE *tmpfile;
		char testfile[MAX_WADPATH];

		if (!userhome)
		{
#if ((defined (__unix__) && !defined (MSDOS)) || defined(__APPLE__) || defined (UNIXCOMMON)) && !defined (__CYGWIN__) && !defined (DC) && !defined (PSP) && !defined(GP2X)
			I_Error("Please set $HOME to your home directory\n");
#elif defined (_WIN32_WCE) && 0
			if (dedicated)
				snprintf(configfile, sizeof configfile, "/Storage Card/SRB2DEMO/d"CONFIGFILENAME);
			else
				snprintf(configfile, sizeof configfile, "/Storage Card/SRB2DEMO/"CONFIGFILENAME);
#else
			if (dedicated)
				snprintf(configfile, sizeof configfile, "d"CONFIGFILENAME);
			else
				snprintf(configfile, sizeof configfile, CONFIGFILENAME);
#endif
		}
		else
		{
			// use user specific config file
#ifdef DEFAULTDIR
			snprintf(srb2home, sizeof srb2home, "%s" PATHSEP DEFAULTDIR, userhome);
			snprintf(downloaddir, sizeof downloaddir, "%s" PATHSEP "DOWNLOAD", srb2home);
			if (dedicated)
				snprintf(configfile, sizeof configfile, "%s" PATHSEP "d"CONFIGFILENAME, srb2home);
			else
				snprintf(configfile, sizeof configfile, "%s" PATHSEP CONFIGFILENAME, srb2home);

			// can't use sprintf since there is %u in savegamename
			strcatbf(savegamename, srb2home, PATHSEP);

			I_mkdir(srb2home, 0700);
#else
			snprintf(srb2home, sizeof srb2home, "%s", userhome);
			snprintf(downloaddir, sizeof downloaddir, "%s", userhome);
			if (dedicated)
				snprintf(configfile, sizeof configfile, "%s" PATHSEP "d"CONFIGFILENAME, userhome);
			else
				snprintf(configfile, sizeof configfile, "%s" PATHSEP CONFIGFILENAME, userhome);

			// can't use sprintf since there is %u in savegamename
			strcatbf(savegamename, userhome, PATHSEP);
#endif
		}

		configfile[sizeof configfile - 1] = '\0';

		// If config isn't writable, tons of behavior will be broken.
		// Fail loudly before things get confusing!
		snprintf(testfile, sizeof testfile, "%s" PATHSEP "file.tmp", srb2home);
		testfile[sizeof testfile - 1] = '\0';

		tmpfile = fopen(testfile, "w");
		if (tmpfile == NULL)
		{
#if defined (_WIN32)
			I_Error("Couldn't write game config.\nMake sure the game is installed somewhere it has write permissions.\n\n(Don't use the Downloads folder, Program Files, or your desktop!\nIf unsure, we recommend making a subfolder in your Documents folder.)");
#else
			I_Error("Couldn't write game config.\nMake sure you've installed the game somewhere it has write permissions.");
#endif
		}
		else
		{
			fclose(tmpfile);
			remove(testfile);
		}

#ifdef _arch_dreamcast
	strcpy(downloaddir, "/ram"); // the dreamcast's TMP
#endif
	}

	// rand() needs seeded regardless of password
	srand((unsigned int)time(NULL));

	if (M_CheckParm("-password") && M_IsNextParm())
		D_SetPassword(M_GetNextParm());

	// add any files specified on the command line with -file wadfile
	// to the wad list
	if (!(M_CheckParm("-connect") && !M_CheckParm("-server")))
	{
		if (M_CheckParm("-file"))
		{
			// the parms after p are wadfile/lump names,
			// until end of parms or another - preceded parm
			while (M_IsNextParm())
			{
				const char *s = M_GetNextParm();

				if (s) // Check for NULL?
					D_AddFile(s, startuppwads);
			}
		}
	}

	// get map from parms

	if (M_CheckParm("-server") || dedicated)
		netgame = server = true;

	CONS_Printf("Z_Init(): Init zone memory allocation daemon. \n");
	Z_Init();
	CONS_Printf("PS3DBG: Z_Init returned\n");

	// adapt tables to SRB2's needs, including extra slots for dehacked file support
	P_PatchInfoTables();
	CONS_Printf("PS3DBG: P_PatchInfoTables returned\n");

	//---------------------------------------------------- READY TIME
	// we need to check for dedicated before initialization of some subsystems

	CONS_Printf("I_InitializeTime()...\n");
	I_InitializeTime();

	// Make backups of some SOCcable tables.
	P_BackupTables();

	// Setup default unlockable conditions
	M_SetupDefaultConditionSets();

	// Setup character tables
	// Have to be done here before files are loaded
	M_InitCharacterTables();

	// load wad, including the main wad file
	CONS_Printf("W_InitMultipleFiles(): Adding IWAD and main PWADs.\n");
	if (!W_InitMultipleFiles(startupwadfiles, false))
#ifdef _DEBUG
		CONS_Error("A WAD file was not found or not valid.\nCheck the log to see which ones.\n");
#else
		I_Error("A WAD file was not found or not valid.\nCheck the log to see which ones.\n");
#endif
	D_CleanFile(startupwadfiles);

	mainwads = 0;

#ifndef DEVELOP
	// Check MD5s of autoloaded files
	// Note: Do not add any files that ignore MD5!
	W_VerifyFileMD5(mainwads, ASSET_HASH_SRB2_SRB);						// srb2.srb/srb2.wad
#ifdef USE_PATCH_DTA
	mainwads++; W_VerifyFileMD5(mainwads, ASSET_HASH_PATCH_DTA);		// patch.dta
#endif
	mainwads++; W_VerifyFileMD5(mainwads, ASSET_HASH_GFX_KART);			// gfx.kart
	mainwads++; W_VerifyFileMD5(mainwads, ASSET_HASH_TEXTURES_KART);	// textures.kart
	mainwads++; W_VerifyFileMD5(mainwads, ASSET_HASH_CHARS_KART);		// chars.kart
	mainwads++; W_VerifyFileMD5(mainwads, ASSET_HASH_MAPS_KART);		// maps.kart -- 4 - If you touch this, make sure to touch up the majormods stuff below.
#ifdef USE_PATCH_KART
	mainwads++; W_VerifyFileMD5(mainwads, ASSET_HASH_PATCH_KART);		// patch.kart
#endif
#else
#ifdef USE_PATCH_DTA
	mainwads++;	// patch.dta
#endif
	mainwads++;	// gfx.kart
	mainwads++;	// textures.kart
	mainwads++;	// chars.kart
	mainwads++;	// maps.kart
#ifdef USE_PATCH_KART
	mainwads++;	// patch.kart
#endif

#endif //ifndef DEVELOP

	//
	// search for maps
	//
	for (wadnum = 0; wadnum < mainwads; wadnum++)
	{
		lumpinfo = wadfiles[wadnum]->lumpinfo;
		for (i = 0; i < wadfiles[wadnum]->numlumps; i++, lumpinfo++)
		{
			name = lumpinfo->name;

			if (name[0] == 'M' && name[1] == 'A' && name[2] == 'P') // Ignore the headers
			{
				INT16 num;
				if (name[5] != '\0')
					continue;
				num = (INT16)M_MapNumber(name[3], name[4]);

				// we want to record whether this map exists. if it doesn't have a header, we can assume it's not relephant
				if (num <= NUMMAPS && mapheaderinfo[num - 1])
				{
					mapheaderinfo[num - 1]->menuflags |= LF2_EXISTSHACK;
				}
			}
		}
	}

	if (!W_InitMultipleFiles(startuppwads, true))
		CONS_Error("A PWAD file was not found or not valid.\nCheck the log to see which ones.\n");
	D_CleanFile(startuppwads);

	//
	// search for maps... again.
	//
	for (wadnum = mainwads+1; wadnum < numwadfiles; wadnum++)
	{
		lumpinfo = wadfiles[wadnum]->lumpinfo;
		for (i = 0; i < wadfiles[wadnum]->numlumps; i++, lumpinfo++)
		{
			name = lumpinfo->name;

			if (name[0] == 'M' && name[1] == 'A' && name[2] == 'P') // Ignore the headers
			{
				INT16 num;
				if (name[5] != '\0')
					continue;
				num = (INT16)M_MapNumber(name[3], name[4]);

				// we want to record whether this map exists. if it doesn't have a header, we can assume it's not relephant
				if (num <= NUMMAPS && mapheaderinfo[num - 1])
				{
					if (mapheaderinfo[num - 1]->menuflags & LF2_EXISTSHACK)
						G_SetGameModified(multiplayer, true); // oops, double-defined - no record attack privileges for you
					mapheaderinfo[num - 1]->menuflags |= LF2_EXISTSHACK;
				}

				CONS_Printf("%s\n", name);
			}
		}
	}

	cht_Init();

	//---------------------------------------------------- READY SCREEN
	// we need to check for dedicated before initialization of some subsystems

	CONS_Printf("I_StartupGraphics()...\n");
	I_StartupGraphics();
#ifdef _PS3
	{
		FILE *ps3f = fopen(PS3_DebugPath("psdebug.txt"), "a");
		if (ps3f) { fputs("O after I_StartupGraphics call returns\n", ps3f); fflush(ps3f); fclose(ps3f); }
	}
#endif

#ifdef HWRENDER
	if (rendermode == render_opengl)
	{
		for (i = 0; i < numwadfiles; i++)
			HWR_LoadShaders(i, (wadfiles[i]->type == RET_PK3));
	}
#endif

	//--------------------------------------------------------- CONSOLE
	// setup loading screen
	SCR_Startup();
	ps3m("P1 after SCR_Startup");

	// we need the font of the console
	CONS_Printf("HU_Init(): Setting up heads up display.\n");
	HU_Init();
	ps3m("P2 after HU_Init");

	COM_Init();
	ps3m("P3 after COM_Init");
	// libogc has a CON_Init function, we must rename SRB2's CON_Init in WII/libogc
#ifndef _WII
	CON_Init();
	ps3m("P4 after CON_Init");
#else
	CON_InitWii();
#endif

	D_RegisterServerCommands();
	ps3m("P5 after D_RegisterServerCommands");
	D_RegisterClientCommands(); // be sure that this is called before D_CheckNetGame
	ps3m("P6 after D_RegisterClientCommands");
	R_RegisterEngineStuff();
	ps3m("P7 after R_RegisterEngineStuff");
	S_RegisterSoundStuff();
	ps3m("P8 after S_RegisterSoundStuff");

	I_RegisterSysCommands();
	ps3m("P9 after I_RegisterSysCommands");

	//--------------------------------------------------------- CONFIG.CFG
	M_FirstLoadConfig(); // WARNING : this do a "COM_BufExecute()"
	ps3m("P10 after M_FirstLoadConfig");

	G_LoadGameData();
	ps3m("P11 after G_LoadGameData");

#if (defined (__unix__) && !defined (MSDOS)) || defined (UNIXCOMMON) || defined (HAVE_SDL)
	VID_PrepareModeList(); // Regenerate Modelist according to cv_fullscreen
	ps3m("P12 after VID_PrepareModeList");
#endif

	// set user default mode or mode set at cmdline
	SCR_CheckDefaultMode();
	ps3m("P13 after SCR_CheckDefaultMode");

	wipegamestate = gamestate;

	savedata.lives = 0; // flag this as not-used

	//------------------------------------------------ COMMAND LINE PARAMS

	// this must be done after loading gamedata,
	// to avoid setting off the corrupted gamedata code in G_LoadGameData if a SOC with custom gamedata is added
	// -- Monster Iestyn 20/02/20
	if (M_CheckParm("-warp") && M_IsNextParm())
	{
		const char *word = M_GetNextParm();
		pstartmap = G_FindMapByNameOrCode(word, 0);
		if (! pstartmap)
			I_Error("Cannot find a map remotely named '%s'\n", word);
		else
		{
			if (!M_CheckParm("-server"))
				G_SetGameModified(true, true);
			autostart = true;
		}
	}

	// Initialize CD-Audio
	if (M_CheckParm("-usecd") && !dedicated)
		I_InitCD();

	if (M_CheckParm("-noupload"))
		COM_BufAddText("downloading 0\n");

	CONS_Printf("M_Init(): Init miscellaneous info.\n");
	M_Init();
	ps3m("P14 after M_Init");

	CONS_Printf("R_Init(): Init SRB2 refresh daemon.\n");
	R_Init();
	ps3m("P15 after R_Init");

	// setting up sound
	if (dedicated)
	{
		sound_disabled = true;
		digital_disabled = true;
#ifndef NO_MIDI
		midi_disabled = true;
#endif
	}
	if (M_CheckParm("-noaudio")) // combines -nosound and -nomusic
	{
		sound_disabled = true;
		digital_disabled = true;
#ifndef NO_MIDI
		midi_disabled = true;
#endif
	}
	else
	{
		if (M_CheckParm("-nosound"))
			sound_disabled = true;
		if (M_CheckParm("-nomusic")) // combines -nomidimusic and -nodigmusic
		{
			digital_disabled = true;
#ifndef NO_MIDI
			midi_disabled = true;
#endif
		}
		else
		{
#ifndef NO_MIDI
			if (M_CheckParm("-nomidimusic"))
				midi_disabled = true; // WARNING: DOS version initmusic in I_StartupSound
#endif
			if (M_CheckParm("-nodigmusic"))
				digital_disabled = true; // WARNING: DOS version initmusic in I_StartupSound
		}
	}
	if (!( sound_disabled && digital_disabled
#ifndef NO_MIDI
				&& midi_disabled
#endif
	 ))
	{
		CONS_Printf("S_InitSfxChannels(): Setting up sound channels.\n");
#ifdef _PS3
		// 2026-08-26 -- bisection knob, temporary, NOT a shipping option.
		// The audio device opens and starts an SDL callback thread even
		// though nothing is audible (SDL_OpenAudio is called with the same
		// pointer for desired and obtained, and the psl1ght backend only
		// takes AUDIO_F32MSB, so I_UpdateStream just memsets). P_SetupLevel
		// calls S_StopSounds()/S_ClearSfx() and then Z_FreeTags(PU_LEVEL..),
		// which frees sfx data the audio thread may still be walking. That
		// race would only ever fire on a level load -- which is exactly the
		// pattern: the title screen survives 183s, every death needs the
		// level path. Skipping the device removes the second thread.
		if (!ps3_noaudio)
		{
#endif
		I_StartupSound();
		ps3m("P16 after I_StartupSound");
		I_InitMusic();
		ps3m("P17 after I_InitMusic");
#ifdef _PS3
		}
		else
			CONS_Printf("[PS3] audio device NOT opened (ps3_noaudio bisection)\n");
#endif
		S_InitSfxChannels(cv_soundvolume.value);
		ps3m("P18 after S_InitSfxChannels");
		S_InitMusicDefs();
		ps3m("P19 after S_InitMusicDefs");
	}

	CONS_Printf("ST_Init(): Init status bar.\n");
	ST_Init();
	ps3m("P20 after ST_Init");

	// Set up splitscreen players before joining!
	if (!dedicated && (M_CheckParm("-splitscreen") && M_IsNextParm()))
	{
		UINT8 num = atoi(M_GetNextParm());
		if (num >= 1 && num <= 4)
		{
			CV_StealthSetValue(&cv_splitplayers, num);
			splitscreen = num-1;
			SplitScreen_OnChange();
		}
	}

	// init all NETWORK
	CONS_Printf("D_CheckNetGame(): Checking network game status.\n");
	if (D_CheckNetGame())
		autostart = true;
	ps3m("P21 after D_CheckNetGame");

	if (splitscreen && !M_CheckParm("-connect")) // Make sure multiplayer & autostart is set if you have splitscreen, even after D_CheckNetGame
		multiplayer = autostart = true;

	// check for a driver that wants intermission stats
	// start the apropriate game based on parms
	if (M_CheckParm("-metal"))
	{
		G_RecordMetal();
		autostart = true;
	}
	else if (M_CheckParm("-record") && M_IsNextParm())
	{
		G_RecordDemo(M_GetNextParm());
		autostart = true;
	}

	// user settings come before "+" parameters.
	if (dedicated)
		COM_ImmedExecute(va("exec \"%s"PATHSEP"kartserv.cfg\"\n", srb2home));
	else
		COM_ImmedExecute(va("exec \"%s"PATHSEP"kartexec.cfg\" -noerror\n", srb2home));

	if (!autostart)
		M_PushSpecialParameters(); // push all "+" parameters at the command buffer

	// demo doesn't need anymore to be added with D_AddFile()
	p = M_CheckParm("-playdemo");
	if (!p)
		p = M_CheckParm("-timedemo");
	if (p && M_IsNextParm())
	{
		char tmp[MAX_WADPATH];
		// add .lmp to identify the EXTERNAL demo file
		// it is NOT possible to play an internal demo using -playdemo,
		// rather push a playdemo command.. to do.

		strcpy(tmp, M_GetNextParm());
		// get spaced filename or directory
		while (M_IsNextParm())
		{
			strcat(tmp, " ");
			strcat(tmp, M_GetNextParm());
		}

		FIL_DefaultExtension(tmp, ".lmp");

		CONS_Printf(M_GetText("Playing demo %s.\n"), tmp);

		if (M_CheckParm("-playdemo"))
		{
			demo.quitafterplaying = true; // quit after one demo
			G_DeferedPlayDemo(tmp);
		}
		else
			G_TimeDemo(tmp);

		G_SetGamestate(GS_NULL);
		wipegamestate = GS_NULL;
		return;
	}

	/*if (M_CheckParm("-ultimatemode"))
	{
		autostart = true;
		ultimatemode = true;
	}*/

	if (autostart || netgame)
	{
		gameaction = ga_nothing;

		CV_ClearChangedFlags();

		// Do this here so if you run SRB2 with eg +timelimit 5, the time limit counts
		// as having been modified for the first game.
		M_PushSpecialParameters(); // push all "+" parameter at the command buffer

		COM_BufExecute(); // ensure the command buffer gets executed before the map starts (+skin)

		strncpy(connectedservername, cv_servername.string, MAXSERVERNAME);

		if (M_CheckParm("-gametype") && M_IsNextParm())
		{
			// from Command_Map_f
			INT32 j;
			INT16 newgametype = -1;
			const char *sgametype = M_GetNextParm();

			newgametype = G_GetGametypeByName(sgametype);

			if (newgametype == -1) // reached end of the list with no match
			{
				j = atoi(sgametype); // assume they gave us a gametype number, which is okay too
				if (j >= 0 && j < NUMGAMETYPES)
					newgametype = (INT16)j;
			}

			if (newgametype != -1)
			{
				j = gametype;
				gametype = newgametype;
				D_GameTypeChanged(j);
			}
		}

		if (M_CheckParm("-skill") && M_IsNextParm())
		{
			INT32 j;
			INT16 newskill = -1;
			const char *sskill = M_GetNextParm();

			for (j = 0; kartspeed_cons_t[j].strvalue; j++)
				if (!strcasecmp(kartspeed_cons_t[j].strvalue, sskill))
				{
					newskill = (INT16)kartspeed_cons_t[j].value;
					break;
				}
			if (!kartspeed_cons_t[j].strvalue) // reached end of the list with no match
			{
				j = atoi(sskill); // assume they gave us a skill number, which is okay too
				if (j >= 0 && j <= 2)
					newskill = (INT16)j;
			}

			if (newskill != -1)
				CV_SetValue(&cv_kartspeed, newskill);
		}

		if (server && !M_CheckParm("+map"))
		{
			// Prevent warping to nonexistent levels
			if (W_CheckNumForName(G_BuildMapName(pstartmap)) == LUMPERROR)
				I_Error("Could not warp to %s (map not found)\n", G_BuildMapName(pstartmap));
			// Prevent warping to locked levels
			// ... unless you're in a dedicated server.  Yes, technically this means you can view any level by
			// running a dedicated server and joining it yourself, but that's better than making dedicated server's
			// lives hell.
			else if (!dedicated && M_MapLocked(pstartmap))
				I_Error("You need to unlock this level before you can warp to it!\n");
			else
				D_MapChange(pstartmap, gametype, (boolean)cv_kartencore.value, true, 0, false, false);
		}
	}
	else if (M_CheckParm("-skipintro"))
	{
		F_StartTitleScreen();
	}
	else
		F_StartIntro(); // Tails 03-03-2002
	ps3m("P22 after intro/title screen setup");

	CON_ToggleOff();
	ps3m("P23 after CON_ToggleOff");

	if (dedicated && server)
	{
		pagename = "TITLESKY";
		levelstarttic = gametic;
		G_SetGamestate(GS_LEVEL);
		if (!P_SetupLevel(false))
			I_Quit(); // fail so reset game stuff
	}

#ifdef HAVE_DISCORDRPC
	if (! dedicated)
	{
		DRPC_Init();
	}
#endif
	ps3m("P24 end of D_SRB2Main");
}

const char *D_Home(void)
{
	const char *userhome = NULL;

#ifdef ANDROID
	return "/data/data/org.srb2/";
#endif
#ifdef _PS3
	// Writable, persistent storage for config, saves and the debug logs.
	//
	// 2026-08-26: prefer the package's own USRDIR when the title is actually
	// installed. Launched from the XMB there is no /app_home and nothing else
	// is reliably writable, so a package that kept writing to a hardcoded
	// /dev_hdd0/game/SRB2KART/ would silently lose its config and, worse, its
	// psdebugS.txt -- which is the only way we can see what a run did on real
	// hardware. Fall back to the old path when that directory is absent, so
	// running the bare .self under RPCS3 keeps behaving exactly as before.
	{
		struct stat ps3st;

		if (stat(PS3_INSTALLDIR, &ps3st) == 0 && S_ISDIR(ps3st.st_mode))
			return PS3_INSTALLDIR "/";

		return "/dev_hdd0/game/SRB2KART/";
	}
#endif
#ifdef _arch_dreamcast
	char VMUHOME[] = "HOME=/vmu/a1";
	putenv(VMUHOME); //don't use I_PutEnv
#endif

	if (M_CheckParm("-home") && M_IsNextParm())
		userhome = M_GetNextParm();
	else
	{
#if defined (GP2X)
		usehome = false; //let use the CWD
		return NULL;
#elif !((defined (__unix__) && !defined (MSDOS)) || defined(__APPLE__) || defined (UNIXCOMMON)) && !defined (__APPLE__) && !defined(_WIN32_WCE)
		if (FIL_FileOK(CONFIGFILENAME))
			usehome = false; // Let's NOT use home
		else
#endif
			userhome = I_GetEnv("HOME"); //Alam: my new HOME for srb2
	}
#if defined (_WIN32) && !defined(_WIN32_WCE) //Alam: only Win32 have APPDATA and USERPROFILE
	if (!userhome && usehome) //Alam: Still not?
	{
		char *testhome = NULL;
		testhome = I_GetEnv("APPDATA");
		if (testhome != NULL
			&& (FIL_FileOK(va("%s" PATHSEP "%s" PATHSEP CONFIGFILENAME, testhome, DEFAULTDIR))))
		{
			userhome = testhome;
		}
	}
#ifndef __CYGWIN__
	if (!userhome && usehome) //Alam: All else fails?
	{
		char *testhome = NULL;
		testhome = I_GetEnv("USERPROFILE");
		if (testhome != NULL
			&& (FIL_FileOK(va("%s" PATHSEP "%s" PATHSEP CONFIGFILENAME, testhome, DEFAULTDIR))))
		{
			userhome = testhome;
		}
	}
#endif// !__CYGWIN__
#endif// _WIN32
	if (usehome) return userhome;
	else return NULL;
}
